repos:
  # ruff - sorting imports and quality checking
  # https://beta.ruff.rs/docs/usage/#pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.280
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=ruff.toml]
      
  # black - formatting
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black