[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"
name = "segretini-matplottini"
description = "A collection of useful Matplolib and Seaborn tips & tricks collected over years of colorful plot-making"
authors = [{name = "Alberto Parravicini", email = "alberto.parravicini@polimi.it"}]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">= 3.7"
dependencies = [
    "seaborn >= 0.12.0",
    "scipy >= 1.3",
    "statsmodels >= 0.10",
    "black >= 22.8",
    "scikit-learn >= 1.1.2",
]

[tool.setuptools]
packages = ["segretini_matplottini"]

[tool.black]
line-length = 119
target-version = ["py37"]