name: segretini_matplottini_pull_request_workflow

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install ".[dev]" --upgrade pip
      - name: Black
        run: |
          black . --config pyproject.toml --check
      - name: Mypy
        run: |
          mypy . --config mypy.ini
      - name: Ruff
        run: |
          ruff . --config ruff.toml
      - name: Test with pytest
        run: |
          pytest
